package bean;
// Generated 18/09/2023 08:19:18 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcmCompras generated by hbm2java
 */
@Entity
@Table(name="bcm_compras"
    ,catalog="db_bruno_monteiro"
)
public class BcmCompras  implements java.io.Serializable {


     private int idbcmCompras;
     private BcmFornecedores bcmFornecedores;
     private BcmFuncionarios bcmFuncionarios;
     private BcmProdutos bcmProdutos;
     private BcmUsuarios bcmUsuarios;
     private String bcmPreco;
     private Date bcmDataCompra;
     private BcmComprasProduto bcmComprasProduto;

    public BcmCompras() {
    }

	
    public BcmCompras(int idbcmCompras, BcmFornecedores bcmFornecedores, BcmFuncionarios bcmFuncionarios, BcmProdutos bcmProdutos, BcmUsuarios bcmUsuarios, String bcmPreco, Date bcmDataCompra) {
        this.idbcmCompras = idbcmCompras;
        this.bcmFornecedores = bcmFornecedores;
        this.bcmFuncionarios = bcmFuncionarios;
        this.bcmProdutos = bcmProdutos;
        this.bcmUsuarios = bcmUsuarios;
        this.bcmPreco = bcmPreco;
        this.bcmDataCompra = bcmDataCompra;
    }
    public BcmCompras(int idbcmCompras, BcmFornecedores bcmFornecedores, BcmFuncionarios bcmFuncionarios, BcmProdutos bcmProdutos, BcmUsuarios bcmUsuarios, String bcmPreco, Date bcmDataCompra, BcmComprasProduto bcmComprasProduto) {
       this.idbcmCompras = idbcmCompras;
       this.bcmFornecedores = bcmFornecedores;
       this.bcmFuncionarios = bcmFuncionarios;
       this.bcmProdutos = bcmProdutos;
       this.bcmUsuarios = bcmUsuarios;
       this.bcmPreco = bcmPreco;
       this.bcmDataCompra = bcmDataCompra;
       this.bcmComprasProduto = bcmComprasProduto;
    }
   
     @Id 

    
    @Column(name="idbcm_compras", unique=true, nullable=false)
    public int getIdbcmCompras() {
        return this.idbcmCompras;
    }
    
    public void setIdbcmCompras(int idbcmCompras) {
        this.idbcmCompras = idbcmCompras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbcm_fornecedores", nullable=false)
    public BcmFornecedores getBcmFornecedores() {
        return this.bcmFornecedores;
    }
    
    public void setBcmFornecedores(BcmFornecedores bcmFornecedores) {
        this.bcmFornecedores = bcmFornecedores;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbcm_funcionarios", nullable=false)
    public BcmFuncionarios getBcmFuncionarios() {
        return this.bcmFuncionarios;
    }
    
    public void setBcmFuncionarios(BcmFuncionarios bcmFuncionarios) {
        this.bcmFuncionarios = bcmFuncionarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbcm_produtos", nullable=false)
    public BcmProdutos getBcmProdutos() {
        return this.bcmProdutos;
    }
    
    public void setBcmProdutos(BcmProdutos bcmProdutos) {
        this.bcmProdutos = bcmProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbcm_usuarios", nullable=false)
    public BcmUsuarios getBcmUsuarios() {
        return this.bcmUsuarios;
    }
    
    public void setBcmUsuarios(BcmUsuarios bcmUsuarios) {
        this.bcmUsuarios = bcmUsuarios;
    }

    
    @Column(name="bcm_Preco", nullable=false, length=1000)
    public String getBcmPreco() {
        return this.bcmPreco;
    }
    
    public void setBcmPreco(String bcmPreco) {
        this.bcmPreco = bcmPreco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bcm_DataCompra", nullable=false, length=10)
    public Date getBcmDataCompra() {
        return this.bcmDataCompra;
    }
    
    public void setBcmDataCompra(Date bcmDataCompra) {
        this.bcmDataCompra = bcmDataCompra;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="bcmCompras")
    public BcmComprasProduto getBcmComprasProduto() {
        return this.bcmComprasProduto;
    }
    
    public void setBcmComprasProduto(BcmComprasProduto bcmComprasProduto) {
        this.bcmComprasProduto = bcmComprasProduto;
    }




}


