package bean;
// Generated 18/09/2023 08:19:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BcmComprasProduto generated by hbm2java
 */
@Entity
@Table(name="bcm_comprasProduto"
    ,catalog="db_bruno_monteiro"
)
public class BcmComprasProduto  implements java.io.Serializable {


     private int idbcmComprasProduto;
     private BcmCompras bcmCompras;
     private int idbcmProdutos;
     private int idbcmCompras;
     private String bcmQuantia;
     private String bcmDataCompra;

    public BcmComprasProduto() {
    }

    public BcmComprasProduto(BcmCompras bcmCompras, int idbcmProdutos, int idbcmCompras, String bcmQuantia, String bcmDataCompra) {
       this.bcmCompras = bcmCompras;
       this.idbcmProdutos = idbcmProdutos;
       this.idbcmCompras = idbcmCompras;
       this.bcmQuantia = bcmQuantia;
       this.bcmDataCompra = bcmDataCompra;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="bcmCompras"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idbcm_comprasProduto", unique=true, nullable=false)
    public int getIdbcmComprasProduto() {
        return this.idbcmComprasProduto;
    }
    
    public void setIdbcmComprasProduto(int idbcmComprasProduto) {
        this.idbcmComprasProduto = idbcmComprasProduto;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public BcmCompras getBcmCompras() {
        return this.bcmCompras;
    }
    
    public void setBcmCompras(BcmCompras bcmCompras) {
        this.bcmCompras = bcmCompras;
    }

    
    @Column(name="idbcm_produtos", nullable=false)
    public int getIdbcmProdutos() {
        return this.idbcmProdutos;
    }
    
    public void setIdbcmProdutos(int idbcmProdutos) {
        this.idbcmProdutos = idbcmProdutos;
    }

    
    @Column(name="idbcm_compras", nullable=false)
    public int getIdbcmCompras() {
        return this.idbcmCompras;
    }
    
    public void setIdbcmCompras(int idbcmCompras) {
        this.idbcmCompras = idbcmCompras;
    }

    
    @Column(name="bcm_Quantia", nullable=false, length=45)
    public String getBcmQuantia() {
        return this.bcmQuantia;
    }
    
    public void setBcmQuantia(String bcmQuantia) {
        this.bcmQuantia = bcmQuantia;
    }

    
    @Column(name="bcm_dataCompra", nullable=false, length=45)
    public String getBcmDataCompra() {
        return this.bcmDataCompra;
    }
    
    public void setBcmDataCompra(String bcmDataCompra) {
        this.bcmDataCompra = bcmDataCompra;
    }




}


