package bean;
// Generated 18/09/2023 08:19:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcmUsuarios generated by hbm2java
 */
@Entity
@Table(name="bcm_usuarios"
    ,catalog="db_bruno_monteiro"
)
public class BcmUsuarios  implements java.io.Serializable {


     private int idbcmUsuarios;
     private String bcmNome;
     private String bcmApelido;
     private String bcmCpf;
     private Date bcmDataNascimento;
     private String bcmSenha;
     private int bcmNivel;
     private String bcmAtivo;
     private Set bcmComprases = new HashSet(0);

    public BcmUsuarios() {
    }

	
    public BcmUsuarios(int idbcmUsuarios, String bcmNome, String bcmApelido, String bcmCpf, Date bcmDataNascimento, String bcmSenha, int bcmNivel, String bcmAtivo) {
        this.idbcmUsuarios = idbcmUsuarios;
        this.bcmNome = bcmNome;
        this.bcmApelido = bcmApelido;
        this.bcmCpf = bcmCpf;
        this.bcmDataNascimento = bcmDataNascimento;
        this.bcmSenha = bcmSenha;
        this.bcmNivel = bcmNivel;
        this.bcmAtivo = bcmAtivo;
    }
    public BcmUsuarios(int idbcmUsuarios, String bcmNome, String bcmApelido, String bcmCpf, Date bcmDataNascimento, String bcmSenha, int bcmNivel, String bcmAtivo, Set bcmComprases) {
       this.idbcmUsuarios = idbcmUsuarios;
       this.bcmNome = bcmNome;
       this.bcmApelido = bcmApelido;
       this.bcmCpf = bcmCpf;
       this.bcmDataNascimento = bcmDataNascimento;
       this.bcmSenha = bcmSenha;
       this.bcmNivel = bcmNivel;
       this.bcmAtivo = bcmAtivo;
       this.bcmComprases = bcmComprases;
    }
   
     @Id 

    
    @Column(name="idbcm_usuarios", unique=true, nullable=false)
    public int getIdbcmUsuarios() {
        return this.idbcmUsuarios;
    }
    
    public void setIdbcmUsuarios(int idbcmUsuarios) {
        this.idbcmUsuarios = idbcmUsuarios;
    }

    
    @Column(name="bcm_nome", nullable=false, length=100)
    public String getBcmNome() {
        return this.bcmNome;
    }
    
    public void setBcmNome(String bcmNome) {
        this.bcmNome = bcmNome;
    }

    
    @Column(name="bcm_apelido", nullable=false, length=50)
    public String getBcmApelido() {
        return this.bcmApelido;
    }
    
    public void setBcmApelido(String bcmApelido) {
        this.bcmApelido = bcmApelido;
    }

    
    @Column(name="bcm_cpf", nullable=false, length=14)
    public String getBcmCpf() {
        return this.bcmCpf;
    }
    
    public void setBcmCpf(String bcmCpf) {
        this.bcmCpf = bcmCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bcm_dataNascimento", nullable=false, length=10)
    public Date getBcmDataNascimento() {
        return this.bcmDataNascimento;
    }
    
    public void setBcmDataNascimento(Date bcmDataNascimento) {
        this.bcmDataNascimento = bcmDataNascimento;
    }

    
    @Column(name="bcm_senha", nullable=false, length=100)
    public String getBcmSenha() {
        return this.bcmSenha;
    }
    
    public void setBcmSenha(String bcmSenha) {
        this.bcmSenha = bcmSenha;
    }

    
    @Column(name="bcm_nivel", nullable=false)
    public int getBcmNivel() {
        return this.bcmNivel;
    }
    
    public void setBcmNivel(int bcmNivel) {
        this.bcmNivel = bcmNivel;
    }

    
    @Column(name="bcm_ativo", nullable=false, length=1)
    public String getBcmAtivo() {
        return this.bcmAtivo;
    }
    
    public void setBcmAtivo(String bcmAtivo) {
        this.bcmAtivo = bcmAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bcmUsuarios")
    public Set getBcmComprases() {
        return this.bcmComprases;
    }
    
    public void setBcmComprases(Set bcmComprases) {
        this.bcmComprases = bcmComprases;
    }




}


